### ISSUE TITLE
[HELP] stop committing on my repo

### ISSUE THREAD

**Issue by BrycensRanch** [nberlette/gitpod-enhanced#13]
**Describe the bug**
every time I commit it shows ur face instead of mine

**To Reproduce**
git commit -m "chore(repo): commit signing step"

**Expected behavior**
to see my face when committing

**Screenshots**

## DIS YOU?

![image](https://user-images.githubusercontent.com/117921904/218323774-69954370-b028-4f71-993c-085e19160897.png)

**Gitpod IDE (please complete the following information):**
 - VSCode Desktop
 - Unknown
 - GamingLaptop
 - Windows, sshed into GitPod that is running Linux

**Additional context**
I set my own gpg signing key and uploaded to github yet I still see your face!! >:(

**Comment by Romvnly-Gaming** [comment]
I should of read documentation

**Comment by nberlette** [comment]
@BrycensRanch Hey Brycen, I'm really sorry for responding to this so late -- I never got notified of this issue. I'm just now catching up with a ton of stuff I missed over the last 6 months due to some health issues.

Just on a first glance it seems like my username and email are hardcoded somewhere... and the configuration is persisting in places it shouldn't. That's pretty concerning. I'm working on fixing this as we speak.

Once again sorry for the delayed response and the inconvenience of this bug

**Comment by nberlette** [comment]
@BrycensRanch Looks like I just found what was causing this facepalm of a bug. The `GIT_AUTHOR_*` variables were being carried over from the .gitconfig template files during the bootstrap process. At the time I assumed those variables would always be defined by Gitpod during the container build/prebuild steps; but obviously that wasn't the case in your scenario. 

Regardless, it was stupid for me to publish any code into production with configuration fallbacks pointing to my own information. Sorry again for the inconvenience.

It should be fixed now, but in case it isn't I'll leave this issue open for the time being.

**Comment by BrycensRanch** [comment]
Hey, thank you. I've switched back to your gitpod in one of my other repos and it's working great now, thank you so much for the work you've done with this gitpod enhanced development environment. It's very nice to use. I'll be closing now, have a great day and I hope Thanksgiving is gonna be awesome for you, man.
